version: '3.4'

services:
  schoolmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44390
      - ConnectionStrings__DefaultConnection=User ID=schooldb;Password=EzcYD9q5wHfW3wEw;Host=schooldb;Port=5432;Database=schooldb;Pooling=true;
    ports:
      - "55559:80"
      - "44390:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  schooldb:
    ports: 
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=EzcYD9q5wHfW3wEw
      - POSTGRES_USER=schooldb
  dbadmin:
    ports: 
      - "5050:80" 
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGDATA=/tmp   

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"